# Generated by Django 2.0.2 on 2018-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cli', models.IntegerField()),
                ('ponto', models.IntegerField()),
                ('nome_cli', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
            ],
        ),
    ]
