# Generated by Django 2.0.2 on 2018-02-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integratest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Data',
        ),
    ]
