# Generated by Django 2.0.2 on 2018-02-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integratest', '0002_auto_20180228_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cli', models.IntegerField(blank=True, null=True)),
                ('ponto', models.IntegerField(blank=True, null=True)),
                ('nome_cli', models.CharField(blank=True, max_length=45, null=True)),
                ('endereco', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'dados',
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='lat',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='lon',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
